### ISSUE TITLE
Build error after upgrading to flutter 2.2

### ISSUE THREAD

**Issue by edwadjei** [AliHoseinpoor/open_settings#4]
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Xcode build done.                                           41.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    warning: Stale file '/_<MY_PROJECT'S_PATH>_/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/flutter_local_notifications.framework' is located outside of the allowed root paths.
    /Users/edwardae/development/flutter/.pub-cache/hosted/pub.dartlang.org/open_settings-2.0.1/ios/Classes/SwiftOpenSettingsPlugin.swift:14:40: error: 'UIApplicationOpenSettingsURLString' has been renamed to 'UIApplication.openSettingsURLString'
                  if let url = URL(string: UIApplicationOpenSettingsURLString) {
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                           UIApplication.openSettingsURLString
    UIKit.UIApplicationOpenSettingsURLString:3:12: note: 'UIApplicationOpenSettingsURLString' was obsoleted in Swift 4.2
    public let UIApplicationOpenSettingsURLString: String
               ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone SE (2nd generation).
Exited (sigterm)

**Comment by marcojoao** [comment]
I did create a PR that fix this problem, still waiting to be approved to the main breach.

**Comment by scana** [comment]
@A-Edd feel free to use this in your `pubspec.yaml` till it's fixed:
```yaml
  open_settings:
      git:
        url: https://github.com/scana/open_settings.git
        ref: main
```
I only added this commit to that fork: https://github.com/scana/open_settings/commit/7863bc6a49264ca3ddcff392570206ce680db0e9

**Comment by a-edw** [comment]
Thanks! I think you can close the issue now.

**Comment by AliHoseinpoor** [comment]
I apologize to all my friends for the delay in fixing the bug.
The UIApplication problem is now resolved. Thank you all friends
